### ISSUE TITLE
Failed to activate the keyword-pair-matcher package

### ISSUE THREAD

**Issue by susisu** [susisu/keyword-pair-matcher#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.13.6
**Thrown From**: [keyword-pair-matcher](https://github.com/susisu/keyword-pair-matcher) package 0.2.0

### Stack Trace

Failed to activate the keyword-pair-matcher package

```
At Cannot read property 'substring' of undefined

TypeError: Cannot read property 'substring' of undefined
    at Matcher.findKeywordUnderCursor (/Users/susisu/.ghq/github.com/susisu/keyword-pair-matcher/lib/matcher.js:238:39)
    at Matcher.update (/Users/susisu/.ghq/github.com/susisu/keyword-pair-matcher/lib/matcher.js:200:29)
    at /Users/susisu/.ghq/github.com/susisu/keyword-pair-matcher/lib/matcher.js:154:14
    at Config.observeScopedKeyPath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:336057)
    at Config.observe (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:326943)
    at Matcher.observeConfig (/Users/susisu/.ghq/github.com/susisu/keyword-pair-matcher/lib/matcher.js:151:19)
    at new Matcher (/Users/susisu/.ghq/github.com/susisu/keyword-pair-matcher/lib/matcher.js:134:10)
    at /Users/susisu/.ghq/github.com/susisu/keyword-pair-matcher/lib/main.js:17:32
    at Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:425358)
    at KeywordPairMatcher.activate (/Users/susisu/.ghq/github.com/susisu/keyword-pair-matcher/lib/main.js:13:43)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2955986)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2955398)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2953029)
    at activationPromise.activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2955258)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2955201)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379950)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379566)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:329753)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379516)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379134)
    at t.loadState.then (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:642865)
    at <anonymous>
```

**Comment by susisu** [comment]
Fixed in 19408d6
